version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save dependencies cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint JS and CSS code
          command: yarn lint
      - run:
          name: Build extension for Chrome and Firefox
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
